Fix Package-Related Changes in the C2C Learn Page
ballerina-platform/ballerina-dev-website pull request #1528
Opened 2020-11-26 14:11 UTC by praneesha

## Purpose
Fix package-related changes in the C2C Learn page.
> Fixes #

## Check List

- [ ] **Page Addition**
  - [ ] Add `permalink` to pages
  - [ ] If contains empty folder(s), Add front-matter `redirect_to:`

- [ ] **Page Rename**
  - [ ] Add front-matter `redirect_from`
  - [ ] Add front-matter `redirect_to:` (If applicable)

2020-11-26 14:46 UTC, anuruddhal requested changes

2020-11-26 14:46 UTC, anuruddhal commented on swan-lake/learn/deployment/code-to-cloud/code-to-cloud-samples.md
> +2. Replace the content of the `/scaling/src/main.bal` file with the content below.
should be `/scaling/main.bal`

2020-11-27 03:33 UTC, praneesha commented on swan-lake/learn/deployment/code-to-cloud/code-to-cloud-samples.md
> +2. Replace the content of the `/scaling/src/main.bal` file with the content below.
Fixed.

2020-11-27 03:58 UTC, anuruddhal approved these changes

2020-11-27 03:58 UTC, merged