Update OpenAPI learn page command "ballerina" to "bal" command
ballerina-platform/ballerina-dev-website pull request #1683
Opened 2021-01-18 13:36 UTC by lnash94

## Purpose
> $subject
> Fixes [#27680](https://github.com/ballerina-platform/ballerina-lang/issues/27680)

## Check List

- [ ] **Page Addition**
  - [ ] Add `permalink` to pages
  - [ ] If contains empty folder(s), Add front-matter `redirect_to:`

- [ ] **Page Rename**
  - [ ] Add front-matter `redirect_from`
  - [ ] Add front-matter `redirect_to:` (If applicable)

2021-01-18 13:40 UTC, praneesha approved these changes

2021-01-21 06:21 UTC, sameerajayasoma requested changes

2021-01-21 06:21 UTC, sameerajayasoma commented on swan-lake/learn/using-the-openapi-tools.md
> +bal openapi   -i <ballerina file>
This should be: 
bal openapi -i <ballerina-file-path>

The option names are inconsistent throughout this document.

2021-01-21 07:02 UTC, praneesha approved these changes

2021-01-21 07:12 UTC, sameerajayasoma approved these changes

2021-01-21 07:23 UTC, merged