Add deploying k8s in getting started section
ballerina-platform/ballerina-dev-website pull request #3444
Opened 2022-01-25 11:52 UTC by xlight05

## Purpose
Adding a deploying ballerina service into Kubernetes section in the getting started section.

> Fixes #

## Check List

- [ ] **Page Addition**
  - [ ] Add `permalink` to pages
  - [ ] If contains empty folder(s), Add front-matter `redirect_to:`

- [ ] **Page Rename**
  - [ ] Add front-matter `redirect_from`
  - [ ] Add front-matter `redirect_to:` (If applicable)

2022-01-25 13:44 UTC, anuruddhal requested changes

2022-01-25 13:44 UTC, anuruddhal commented on learn/getting-started/deploying-ballerina-on-kubernetes.md
> +listener http:Listener httpListener = new (8080);
Add a new line after the imports

2022-01-25 16:55 UTC, praneesha commented on learn/getting-started/deploying-ballerina-on-kubernetes.md
> +In order to enable the code to cloud functionality in the ballerina project, you need to add `cloud="k8s"` to the build-options in Ballerina.toml
```suggestion
In order to enable the code to cloud functionality in the Ballerina project, you need to add the `cloud="k8s"` property to the build-options in the `Ballerina.toml` file.
```

2022-01-25 16:55 UTC, praneesha commented on learn/getting-started/deploying-ballerina-on-kubernetes.md
> +You can visit the [Code to cloud Deployment guide](/learn/running-ballerina-programs-in-the-cloud/code-to-cloud-deployment.html) for in depth information about executing these deployed applications a
```suggestion
For in-depth information about executing these deployed applications and the supported customizations in code to cloud, see [Code to cloud Deployment](/learn/running-ballerina-programs-in-the-cloud/code-to-cloud-deployment.html).
```
Let's add this as an info section as it was decided to remove the `What's Next` sections.

2022-01-26 09:37 UTC, anuruddhal approved these changes

2022-01-26 09:38 UTC, merged