Revert "Add GraphQL Example to Ballerina-In-Action Section"
ballerina-platform/ballerina-dev-website pull request #3733
Opened 2022-01-31 20:02 UTC by praneesha

Reverts ballerina-platform/ballerina-dev-website#3708

2022-01-31 21:59 UTC, sameerajayasoma requested changes

2022-01-31 21:59 UTC, sameerajayasoma commented on index.html
> -    resource function get search(string id, Currency currency) returns Album|error {
Is search a proper resource name in GraphQL?

2022-01-31 21:59 UTC, sameerajayasoma commented on index.html
> -            json response = check self.httpClient->get("/currencyExchange?" + query);
I would use an application-specific record type here.

2022-01-31 21:59 UTC, sameerajayasoma commented on index.html
> -            json response = check self.httpClient->get("/currencyExchange?" + query);
With that we can remove if/else below

2022-01-31 21:59 UTC, sameerajayasoma commented on index.html
> -        self.httpClient = check new (apiEndpoint);
I would use a meaningful variable name instead of `httpClient`.

2022-02-01 05:25 UTC, ThisaruGuruge commented
Closing as the comments have been addressed in #3748

2022-02-01 05:25 UTC, closed without merging