Update the `Download` page on VS Code content
ballerina-platform/ballerina-dev-website pull request #5598
Opened 2022-10-05 11:03 UTC by praneesha

## Purpose
Update the `Download` page on VS Code content.
> Fixes #

## Checklist

- [ ] **Page addition**
  - [ ] Add `permalink` to pages.

- [ ] **Page removal**
  - [ ] Remove entry from corresponding left nav YAML file.
  - [ ] Add `redirect_from` on the alternative page.
  - [ ] If no alternative page, add redirection on the `redirections.js ` file.

- [ ] **Page rename**
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

- [ ] **Page restrcuture**
  - [ ] Add `permalink` to pages.
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

2022-10-05 12:35 UTC, hevayo requested changes
IMO the download option should be subtle the main button should point to VSCode marketplace and ask the users to get it from there.

2022-10-05 13:55 UTC, praneesha commented
@hevayo - Updated as shown below. Please review and approve.

<img width="1680" alt="Screenshot 2022-10-05 at 19 25 00" src="https://user-images.githubusercontent.com/11707273/194078258-90bd6d0a-e291-4ade-8c1e-73a79f22361b.png">

2022-10-06 06:23 UTC, praneesha commented
Updated again by including the button for the VS Code extension as per the feedback received as shown below.

<img width="1672" alt="Screenshot 2022-10-06 at 11 38 25" src="https://user-images.githubusercontent.com/11707273/194229406-e9f5374b-7ec7-4948-ae66-41ece4eb11c0.png">

2022-10-06 06:34 UTC, hevayo approved these changes

2022-10-06 06:42 UTC, merged