Add steps to resolve the UUID related error to release notes
ballerina-platform/ballerina-dev-website pull request #6201
Opened 2023-01-13 07:12 UTC by MadhukaHarith92

## Purpose
> $Subject

Related to https://github.com/wso2-enterprise/internal-support-ballerina/issues/238

2023-01-13 07:13 UTC, keizer619 approved these changes

2023-01-15 16:58 UTC, praneesha requested changes

2023-01-15 16:58 UTC, praneesha commented on downloads/swan-lake-release-notes/swan-lake-2201.3.0/RELEASE_NOTE.md
> +> If the application has a direct dependency, please modify the UUID version to 1.4.0 through modifying the `Dependencies.toml`. If the dependency is transitive, please make sure to update the corres
```suggestion
>**Note:** If the application has a direct dependency, modify the UUID version to 1.4.0 by modifying the `Dependencies.toml` file. If the dependency is transitive, make sure to update the corresponding package or module to 1.4.0 and use it by updating the `Dependencies.toml` file.
```
Can we summarize and combine the two notes into one?

2023-01-17 03:49 UTC, keizer619 submitted a review, later dismissed

2023-01-17 05:59 UTC, praneesha approved these changes

2023-01-17 06:05 UTC, praneesha submitted a review, later dismissed

2023-01-17 06:14 UTC, keizer619 approved these changes

2023-01-17 06:40 UTC, merged