Add std-lib new features to the release node
ballerina-platform/ballerina-dev-website pull request #7660
Opened 2023-08-24 11:35 UTC by ayeshLK

## Purpose
> $subject

2023-08-24 12:00 UTC, dilanSachi commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +##### `soap` Package
```suggestion
#### `soap` Package
```
Only 4 right?

2023-08-24 19:38 UTC, ayeshLK commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +##### `soap` Package
Fixed with [2d43cbc1bc843446371dbf284c74bae411008443](https://github.com/ballerina-platform/ballerina-dev-website/pull/7660/commits/2d43cbc1bc843446371dbf284c74bae411008443)

2023-08-25 00:20 UTC, praneesha requested changes

2023-08-25 00:20 UTC, praneesha commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +- Introduced the `soap` standard library package, which provides a client API to connect to SOAP enpoints.
```suggestion
- Introduced the `soap` standard library package, which provides a client API to connect to SOAP endpoints.
```
Is it correct to use both `library` and `package` words? Should it be the `soap` package?

2023-08-25 00:20 UTC, praneesha commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +- Introduced the `mqtt` standard library package, which provides an implementation to interact with message brokers using MQTT protocol.
```suggestion
- Introduced the `mqtt` standard library package, which provides an implementation to interact with message brokers using the MQTT protocol.
```
Ditto.

2023-08-25 00:20 UTC, praneesha commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +#### `soap` Package
```suggestion
#### `soap` package
```
All titles should be in sentence case.

2023-08-25 00:20 UTC, praneesha commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +#### `java.jms` Package
```suggestion
#### `java.jms` Package
```
Ditto.

2023-08-25 00:20 UTC, praneesha commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +- Introduced the `java.jms` standard library package, which provides an implementation to interact with message brokers using JMS protocol.
```suggestion
- Introduced the `java.jms` standard library package, which provides an implementation to interact with message brokers using the JMS protocol.
```

2023-08-28 04:20 UTC, ayeshLK commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +#### `mqtt` Package
```suggestion
#### `mqtt` package
```

2023-08-28 04:20 UTC, ayeshLK commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +#### `java.jms` Package
```suggestion
#### `java.jms` package
```

2023-08-28 04:21 UTC, ayeshLK commented on downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> +#### `java.jms` Package
Fixed with [a57393068de956e2d8ae4e43952c3a5514baaf5d](https://github.com/ballerina-platform/ballerina-dev-website/pull/7660/commits/a57393068de956e2d8ae4e43952c3a5514baaf5d)

2023-08-28 04:26 UTC, praneesha approved these changes

2023-08-28 04:33 UTC, MohamedSabthar approved these changes

2023-08-28 04:58 UTC, merged