removed the stray indent code block
ballerina-platform/ballerina-dev-website pull request #8009
Opened 2023-10-09 17:37 UTC by Ln11211

## Purpose
This PR fixes the code block indent for the docs by removing the stray indent code block. This Pr solves the issue #6656 .
> Fixes #

## Checklist

- [ ] **Page addition**
  - [ ] Add `permalink` to pages.

- [ ] **Page removal**
  - [ ] Remove entry from corresponding left nav YAML file.
  - [ ] Add `redirect_from` on the alternative page.
  - [ ] If no alternative page, add redirection on the `redirections.js ` file.

- [ ] **Page rename**
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

- [ ] **Page restrcuture**
  - [ ] Add `permalink` to pages.
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

2023-10-09 17:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/ballerina-dev-website?pullRequest=8009) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/ballerina-dev-website?pullRequest=8009) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/ballerina-dev-website?pullRequest=8009) it.</sub>

2023-10-09 17:52 UTC, Ln11211 commented
Hello @sm1990, To solve the issue of syntax highlighting for nested code, I removed the extra highlighting block inserted within a code block (which I think are stray highlighters) as they are often ignored during language detection and syntax highlighting.

I have made one change to a document to show how removing this extra code indent works. If you think this is ok, then I will proceed to remove other stray code indents I found in other markdown docs.


For example, see the stray indent which prevented the complete syntax highlighting
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/91385411/58c6882e-69a2-4200-9c69-672df66311c8)

2023-10-10 08:48 UTC, sm1990 commented
Hi @Ln11211, 
Thank you for looking into this issue. However, your fix doesn't solve our problem. 

The code snippet in the md file is correct. When creating a Ballerina package, we must also make the relevant documentation. For that, we do the documentation as comments within the code in a `.bal` file, as shown below.

```ballerina
# Calculates the value of the 'a' raised to the power of 'b'.
# ```ballerina
# float aPowerB = math:pow(3.2, 2.4);
# ```
# 
# + a - Base value
# + b - Exponential value
# + return - Calculated exponential value
public isolated function pow(float a, float b) returns float {
    return 0;
}
```

If we need to include a code snippet with our API documentation, we use nested code blocks, as shown above.
We need to show the whole code block (including the nested section) as a Ballerina comment with correct syntax highlighting on our web page.

We control the syntax highlighting using this file https://github.com/ballerina-platform/ballerina-dev-website/blob/master/utils/highlighter.js

Let me know if you have further questions.

2023-10-17 04:16 UTC, sm1990 requested changes
Please address the issues mentioned in https://github.com/ballerina-platform/ballerina-dev-website/pull/8009#issuecomment-1754732787

2023-10-26 10:53 UTC, sm1990 commented
Closing this PR as the issue was fixed via another PR.

2023-10-26 10:53 UTC, closed without merging