Add syntax highlighting to nested code blocks #6656
ballerina-platform/ballerina-dev-website pull request #8102
Opened 2023-10-25 07:46 UTC by ashutuptiwari

## Purpose
> Code blocks with nested syntax was not being highlighted
> Fixes #6656 

## Checklist

- [ ] **Page addition**
  - [ ] Add `permalink` to pages.

- [ ] **Page removal**
  - [ ] Remove entry from corresponding left nav YAML file.
  - [ ] Add `redirect_from` on the alternative page.
  - [ ] If no alternative page, add redirection on the `redirections.js ` file.

- [ ] **Page rename**
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

- [ ] **Page restrcuture**
  - [ ] Add `permalink` to pages.
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

2023-10-25 11:24 UTC, sm1990 requested changes
@ashutuptiwari Thank you for your contribution.

However, your fix breaks for normal code snippets unless we add a space after every ending `. Also if we're accepting this solution, we have to update all our md files and add the space, which is not practical. We need to look for a different method.
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/0eb5ebfb-70fd-4a35-8caa-ad0af23a7ba8)

2023-10-25 12:56 UTC, ashutuptiwari commented
Alright let me try something else

2023-10-26 06:43 UTC, sm1990 commented on swan-lake/development-tutorials/test-document-the-code/generate-code-documentation.md
> +```
Remove the space

2023-10-26 06:43 UTC, sm1990 commented on utils/highlighter.js
> +        console.log(`match:\n  ${match[0]}`);
Remove debug logs.

2023-10-26 06:55 UTC, ashutuptiwari commented
Done @sm1990

2023-10-26 08:23 UTC, sm1990 commented
> Done @sm1990

The fix does seem to work for code snippets within `<li>`s. Test http://localhost:3000/learn/integration-tutorials/sending-a-message-to-a-service/
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/f904b1b4-c7e9-47c3-ade8-d5f1fcbb56f0)

2023-10-26 09:17 UTC, ashutuptiwari commented
fixed that as well @sm1990

2023-10-26 09:58 UTC, sm1990 approved these changes

2023-10-26 09:59 UTC, merged

2023-10-26 10:03 UTC, sm1990 commented
@ashutuptiwari Thank you for your contribution. We are currently hosting a `Ballerina Hacktoberfest`. Since this issue is eligible for our event, please visit https://ballerina.io/hacktoberfest/#rules & submit the form. 😄

2023-10-26 10:11 UTC, ashutuptiwari commented
You're welcome @sm1990 and thank you for your inputs. This was a great learning opportunity. I look forward to contributing more in the future. 
Hasta La Vista